Merge pull request #1 from tonkeeper/main
tonkeeper/ton-assets pull request #1062
Opened 2024-09-08 01:37 UTC by Cambaa

Cambatonkep

Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

2024-09-10 21:25 UTC, Farahnady reviewed
1062

2024-09-11 14:14 UTC, Hamaster2 approved these changes

2024-09-11 23:01 UTC, Jones098 approved these changes

2024-09-12 00:04 UTC, Hamaster2 approved these changes

2024-09-12 11:50 UTC, tiaraton approved these changes

2024-09-12 19:34 UTC, tiaraton approved these changes

2024-09-13 15:16 UTC, Farahnady approved these changes
__pycache__/dexes.cpython-310.pyc

2024-09-13 15:16 UTC, Farahnady commented on __pycache__/dexes.cpython-310.pyc
__pycache__/dexes.cpython-310.pyc

2024-09-14 05:28 UTC, Hamaster2 requested changes
_****_

2024-09-14 05:33 UTC, Hamaster2 reviewed
_*n*

2024-09-15 15:39 UTC, ayanwaar commented on __pycache__/dexes.cpython-310.pyc
its me

2024-09-15 15:39 UTC, ayanwaar approved these changes
all

2024-09-15 18:04 UTC, Hamaster2 approved these changes

2024-09-15 18:07 UTC, Hamaster2 approved these changes

2024-09-15 18:19 UTC, Hamaster2 approved these changes

2024-09-15 19:18 UTC, Jones098 commented on __pycache__/dexes.cpython-310.pyc
Yes

2024-09-15 20:37 UTC, ayanwaar approved these changes

2024-09-16 01:35 UTC, Hamaster2 approved these changes

2024-09-16 01:36 UTC, Hamaster2 approved these changes

2024-09-16 22:53 UTC, Hamaster2 approved these changes

2024-09-17 21:08 UTC, Hamaster2 approved these changes

2024-09-17 21:28 UTC, Hamaster2 approved these changes

2024-09-17 21:55 UTC, Hamaster2 approved these changes

2024-09-17 21:56 UTC, Hamaster2 approved these changes

2024-09-17 23:06 UTC, Hamaster2 commented on __pycache__/dexes.cpython-310.pyc
Tonhub

2024-09-17 23:06 UTC, Hamaster2 approved these changes

2024-09-19 14:50 UTC, Hamaster2 approved these changes

2024-09-19 16:39 UTC, Hamaster2 approved these changes

2024-09-19 16:39 UTC, Hamaster2 approved these changes

2024-09-20 00:53 UTC, tiaraton approved these changes

2024-09-21 00:36 UTC, ayanwaar approved these changes

2024-09-21 00:36 UTC, ayanwaar commented on jettons.json
holla

2024-09-21 21:06 UTC, ayanwaar approved these changes

2024-09-23 20:44 UTC, Rezacb0413 approved these changes

2024-09-23 20:46 UTC, Rezacb0413 approved these changes

2024-09-24 13:12 UTC, Farahnady approved these changes
# TON Assets

This is a list of popular addresses and assets. We are open to pull request but **please read manual in the end of this readme for PR**.

## Addresses

Short list. Full in [accounts.json](accounts.json)

Name           | Address
---------------|-----------
%s


## NFT collections

Name           | Address
---------------|-----------
%s


## Jettons

Name           | Address
---------------|-----------
%s


## Structure

Directories `accounts`, `collections` and `jettons` contain source data. If you want to make pull request - **please commit to this directories only**.
`accounts.json`, `jettons.json`, `collections.json` and `README.md` contains automatically generated data. Please don't commit directly to this files.

2024-09-24 14:03 UTC, Hamaster2 approved these changes

2024-09-25 19:06 UTC, Rezacb0413 approved these changes

2024-09-25 19:06 UTC, Rezacb0413 approved these changes

2024-09-25 23:18 UTC, Hamaster2 approved these changes

2024-09-26 18:15 UTC, Hamaster2 requested changes

2024-09-26 18:15 UTC, Hamaster2 commented on README.md
17f0ce0270a6910d6d464495e3913df8c7322e59

2024-09-28 05:48 UTC, Hamaster2 approved these changes

2024-09-28 05:49 UTC, Hamaster2 approved these changes

2024-09-28 10:57 UTC, Hamaster2 approved these changes

2024-09-28 14:38 UTC, Hamaster2 approved these changes

2024-09-28 17:39 UTC, ReadoneHussein approved these changes

2024-09-28 19:12 UTC, Hamaster2 approved these changes

2024-09-28 21:26 UTC, Hamaster2 approved these changes

2024-09-28 21:28 UTC, Hamaster2 approved these changes

2024-10-01 22:31 UTC, Hamaster2 approved these changes

2024-10-05 20:41 UTC, Hamaster2 commented on jettons.json
[](#)

2024-10-05 20:41 UTC, Hamaster2 approved these changes

2024-10-06 13:18 UTC, DogsMasterv2 commented on README.md
I want to work on this

2024-10-06 13:19 UTC, DogsMasterv2 commented
how to fix this

2024-10-06 14:07 UTC, high089 commented on __pycache__/dexes.cpython-310.pyc
__pycache__/dexes.cpython-310.pyc

2024-10-06 14:52 UTC, Farahnady approved these changes
https://github.com/tonkeeper/ton-assets/pull/1062/commits/d80f3dfe8dc7031af0410baf9174226e17958eb1

2024-10-06 14:53 UTC, Farahnady commented
https://github.com/tonkeeper/ton-assets/pull/1062/commits/d80f3dfe8dc7031af0410baf9174226e17958eb1

2024-10-09 04:49 UTC, Hamaster2 approved these changes

2024-10-09 07:19 UTC, Hamaster2 approved these changes

2024-10-10 10:40 UTC, Hamaster2 approved these changes

2024-10-10 15:22 UTC, Hamaster2 approved these changes

2024-10-10 19:04 UTC, Hamaster2 requested changes
# ۵۶

2024-10-12 13:24 UTC, Hamaster2 approved these changes

2024-10-12 13:26 UTC, Hamaster2 commented on __pycache__/dexes.cpython-310.pyc
<=>

2024-10-12 13:52 UTC, Hamaster2 approved these changes

2024-10-12 13:58 UTC, Hamaster2 reviewed
<=>

2024-10-12 13:58 UTC, Hamaster2 approved these changes

2024-10-12 14:01 UTC, Hamaster2 approved these changes

2024-10-12 14:02 UTC, Hamaster2 commented
56#

2024-10-12 14:03 UTC, Hamaster2 commented
<=> Cambatonkep
> 
> Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.
> 
> 
> Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

2024-10-12 14:03 UTC, Hamaster2 commented
#۵۶####

2024-10-13 04:24 UTC, Hamaster2 approved these changes

2024-10-13 04:25 UTC, Hamaster2 approved these changes

2024-10-20 14:39 UTC, high089 approved these changes

2024-10-24 09:16 UTC, closed without merging

2025-02-22 01:03 UTC, ayanwaar commented
093529635b9f2a94083359e9c446a73dd15dae3a

2025-02-22 01:04 UTC, ayanwaar commented
b89dd78532d194ef24e8ecc458790d0214d8c25d