Create MAGA.yaml
tonkeeper/ton-assets pull request #1143
Opened 2024-09-29 17:43 UTC by Ulipyspirus

Adding a new token MAGA

Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

2024-09-29 18:16 UTC, Ulipyspirus commented
If there are any discrepancies, we can correct the application. Thank you.

2024-09-30 15:38 UTC, tikto29 commented
Ok

2024-09-30 15:39 UTC, tikto29 approved these changes

2024-09-30 15:39 UTC, tikto29 commented
jettons/MAGA.yaml

2024-09-30 15:41 UTC, tikto29 requested changes
jettons/MAGA.yaml

2024-09-30 15:45 UTC, tikto29 approved these changes

2024-10-01 05:34 UTC, Ulipyspirus commented
Is any further intervention needed from our side? Thanks.

2024-11-22 04:23 UTC, Irso007 commented
Tonkeeper reserves the right to refuse token verification.

2024-11-22 04:23 UTC, closed without merging