Manidlfnib@gmail.com
tonkeeper/ton-assets pull request #1196
Opened 2024-10-12 02:16 UTC by Manidlfni1380B

Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

2024-10-12 07:20 UTC, Hamaster2 requested changes

2024-10-12 07:20 UTC, Hamaster2 commented on .github/workflows/python-package-conda.yml
# ۲۴

2024-10-12 07:20 UTC, Hamaster2 commented on .github/workflows/python-package-conda.yml
# ۲۴

2024-10-13 04:18 UTC, high089 approved these changes

2024-10-13 04:18 UTC, high089 commented on .github/workflows/python-package-conda.yml
Hi

2024-10-13 04:21 UTC, Hamaster2 approved these changes

2024-10-13 04:22 UTC, Hamaster2 approved these changes

2024-10-13 04:23 UTC, Hamaster2 approved these changes

2024-10-13 04:23 UTC, Hamaster2 approved these changes

2024-10-17 23:22 UTC, Hamaster2 approved these changes

2024-10-20 14:40 UTC, high089 approved these changes

2024-10-21 09:14 UTC, Hamaster2 approved these changes

2024-10-21 09:15 UTC, Hamaster2 approved these changes

2024-10-21 11:14 UTC, closed without merging