Create SOCENG.yaml
tonkeeper/ton-assets pull request #125
Opened 2024-02-07 21:12 UTC by EOY52

Здравствуйте, хочу добавить свой токен SOCENG, но какой раз уже отклоняют, можно узнать почему?

2024-02-08 21:46 UTC, hadixc requested changes
لطفاً بررسی کنید و بفرستید

2024-02-08 23:21 UTC, EOY52 commented
> لطفاً بررسی کنید и بفرستید

What should I check, is everything filled out correctly?

2024-02-11 00:24 UTC, EOY52 commented
?

2024-02-11 09:03 UTC, hadixc commented
خیلی چیزی رو لغو نمی‌کنم من چیزی رو لغو نخواهم کرد

bazarshahr.com

در تاریخ یکشنبه ۱۱ فوریه ۲۰۲۴،‏ ۰۳:۵۴ EOY52 ***@***.***> نوشت:

> ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tonkeeper/ton-assets/pull/125#issuecomment-1937368443>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BF3F64M5S56NXJ3W3MPBILTYTAFURAVCNFSM6AAAAABC6RAVWCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZXGM3DQNBUGM>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-02-12 20:11 UTC, closed without merging

2024-02-12 21:10 UTC, hadixc commented
بله

bazarshahr.com

در تاریخ دوشنبه ۱۲ فوریه ۲۰۲۴،‏ ۲۳:۴۱ EOY52 ***@***.***> نوشت:

> Closed #125 <https://github.com/tonkeeper/ton-assets/pull/125>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tonkeeper/ton-assets/pull/125#event-11779353277>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BF3F64PI47A3RYR5GJKJCTTYTJZQDAVCNFSM6AAAAABC6RAVWCVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRG43TSMZVGMZDONY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>