Create FLAM.yaml
tonkeeper/ton-assets pull request #262
Opened 2024-03-30 10:01 UTC by flamcoin

Please make sure you change the original ones `.yaml` fiels in directories `accounts/`, `collections/` or  `jettons/` and do not touch automatically generated .json files in the repository root.

Пожалуйста, убедитесь, что вы изменяете исходные `.yaml` файлы в директориях  `accounts/`, `collections/` или  `jettons/` и не трогаете автоматически сгенерированные файлы `.json` в корне репозитория.

2024-04-01 11:14 UTC, Hiyorimi commented
AFAIK, this is a meme token which was launched by [Ghnwd community](https://t.me/ghwnd) out of their genuine curiosity.

Not that I support this token (NFA, DYOR), but really excited to see where it goes.

2024-04-03 08:28 UTC, ivan-tsaryov approved these changes

2024-04-03 08:52 UTC, Dosmantay11 approved these changes

2024-04-03 09:18 UTC, DeXTeR40rus requested changes
image: "https://telegra.ph/file/10c8938bf198117f45e60.png"

2024-04-03 09:25 UTC, youarealll approved these changes

2024-10-30 15:25 UTC, grishkanaruzhka commented
The request has timed out. If you have any questions about token approval, please contact [@tkgregory](https://t.me/tkgregory) on Telegram for further consideration

2024-10-30 15:25 UTC, closed without merging